//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CoreProtocol.proto
namespace dfproto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CoreTextFragment")]
  public partial class CoreTextFragment : global::ProtoBuf.IExtensible
  {
    public CoreTextFragment() {}
    
    private string _text;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }

    private dfproto.CoreTextFragment.Color _color = dfproto.CoreTextFragment.Color.COLOR_BLACK;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(dfproto.CoreTextFragment.Color.COLOR_BLACK)]
    public dfproto.CoreTextFragment.Color color
    {
      get { return _color; }
      set { _color = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Color")]
    public enum Color
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"COLOR_BLACK", Value=0)]
      COLOR_BLACK = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COLOR_BLUE", Value=1)]
      COLOR_BLUE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COLOR_GREEN", Value=2)]
      COLOR_GREEN = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COLOR_CYAN", Value=3)]
      COLOR_CYAN = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COLOR_RED", Value=4)]
      COLOR_RED = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COLOR_MAGENTA", Value=5)]
      COLOR_MAGENTA = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COLOR_BROWN", Value=6)]
      COLOR_BROWN = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COLOR_GREY", Value=7)]
      COLOR_GREY = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COLOR_DARKGREY", Value=8)]
      COLOR_DARKGREY = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COLOR_LIGHTBLUE", Value=9)]
      COLOR_LIGHTBLUE = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COLOR_LIGHTGREEN", Value=10)]
      COLOR_LIGHTGREEN = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COLOR_LIGHTCYAN", Value=11)]
      COLOR_LIGHTCYAN = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COLOR_LIGHTRED", Value=12)]
      COLOR_LIGHTRED = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COLOR_LIGHTMAGENTA", Value=13)]
      COLOR_LIGHTMAGENTA = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COLOR_YELLOW", Value=14)]
      COLOR_YELLOW = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COLOR_WHITE", Value=15)]
      COLOR_WHITE = 15
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CoreTextNotification")]
  public partial class CoreTextNotification : global::ProtoBuf.IExtensible
  {
    public CoreTextNotification() {}
    
    private readonly global::System.Collections.Generic.List<dfproto.CoreTextFragment> _fragments = new global::System.Collections.Generic.List<dfproto.CoreTextFragment>();
    [global::ProtoBuf.ProtoMember(1, Name=@"fragments", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dfproto.CoreTextFragment> fragments
    {
      get { return _fragments; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CoreErrorNotification")]
  public partial class CoreErrorNotification : global::ProtoBuf.IExtensible
  {
    public CoreErrorNotification() {}
    
    private dfproto.CoreErrorNotification.ErrorCode _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public dfproto.CoreErrorNotification.ErrorCode code
    {
      get { return _code; }
      set { _code = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCode")]
    public enum ErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CR_LINK_FAILURE", Value=-3)]
      CR_LINK_FAILURE = -3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CR_WOULD_BREAK", Value=-2)]
      CR_WOULD_BREAK = -2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CR_NOT_IMPLEMENTED", Value=-1)]
      CR_NOT_IMPLEMENTED = -1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CR_OK", Value=0)]
      CR_OK = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CR_FAILURE", Value=1)]
      CR_FAILURE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CR_WRONG_USAGE", Value=2)]
      CR_WRONG_USAGE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CR_NOT_FOUND", Value=3)]
      CR_NOT_FOUND = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EmptyMessage")]
  public partial class EmptyMessage : global::ProtoBuf.IExtensible
  {
    public EmptyMessage() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IntMessage")]
  public partial class IntMessage : global::ProtoBuf.IExtensible
  {
    public IntMessage() {}
    
    private int _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IntListMessage")]
  public partial class IntListMessage : global::ProtoBuf.IExtensible
  {
    public IntListMessage() {}
    
    private readonly global::System.Collections.Generic.List<int> _value = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> value
    {
      get { return _value; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StringMessage")]
  public partial class StringMessage : global::ProtoBuf.IExtensible
  {
    public StringMessage() {}
    
    private string _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StringListMessage")]
  public partial class StringListMessage : global::ProtoBuf.IExtensible
  {
    public StringListMessage() {}
    
    private readonly global::System.Collections.Generic.List<string> _value = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> value
    {
      get { return _value; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CoreBindRequest")]
  public partial class CoreBindRequest : global::ProtoBuf.IExtensible
  {
    public CoreBindRequest() {}
    
    private string _method;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"method", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string method
    {
      get { return _method; }
      set { _method = value; }
    }
    private string _input_msg;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"input_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string input_msg
    {
      get { return _input_msg; }
      set { _input_msg = value; }
    }
    private string _output_msg;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"output_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string output_msg
    {
      get { return _output_msg; }
      set { _output_msg = value; }
    }

    private string _plugin = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"plugin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string plugin
    {
      get { return _plugin; }
      set { _plugin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CoreBindReply")]
  public partial class CoreBindReply : global::ProtoBuf.IExtensible
  {
    public CoreBindReply() {}
    
    private int _assigned_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"assigned_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int assigned_id
    {
      get { return _assigned_id; }
      set { _assigned_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CoreRunCommandRequest")]
  public partial class CoreRunCommandRequest : global::ProtoBuf.IExtensible
  {
    public CoreRunCommandRequest() {}
    
    private string _command;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"command", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string command
    {
      get { return _command; }
      set { _command = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _arguments = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"arguments", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> arguments
    {
      get { return _arguments; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}