# This file runs when DFHack is initialized, when Dwarf Fortress is first
# started, before any save data is loaded.
#
# You can extend or override DFHack's default configuration by adding commands
# to the bottom of this file.

# Load DFHack configuration defaults. If you remove this line, DFHack tools may
# not function as expected.
script hack/init/dfhack.default.init

# Feel free to add your personal configuration commands here:
