# This file runs when a fortress map is loaded, after any onLoad.init files
# (which run earlier, when the world is loaded).
#
# You can extend or override DFHack's default configuration by adding commands
# to the bottom of this file.

# Load DFHack configuration defaults. If you remove these lines, many DFHack
# tools may not function as expected.
script hack/init/onMapLoad.dfhack.init

# Feel free to add your personal configuration commands here:
