//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: isoworldremote.proto
namespace isoworldremote
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EmbarkTileLayer")]
  public partial class EmbarkTileLayer : global::ProtoBuf.IExtensible
  {
    public EmbarkTileLayer() {}
    
    private readonly global::System.Collections.Generic.List<isoworldremote.BasicMaterial> _mat_type_table = new global::System.Collections.Generic.List<isoworldremote.BasicMaterial>();
    [global::ProtoBuf.ProtoMember(4, Name=@"mat_type_table", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<isoworldremote.BasicMaterial> mat_type_table
    {
      get { return _mat_type_table; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _mat_subtype_table = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"mat_subtype_table", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> mat_subtype_table
    {
      get { return _mat_subtype_table; }
    }
  
    private readonly global::System.Collections.Generic.List<isoworldremote.BasicShape> _tile_shape_table = new global::System.Collections.Generic.List<isoworldremote.BasicShape>();
    [global::ProtoBuf.ProtoMember(6, Name=@"tile_shape_table", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<isoworldremote.BasicShape> tile_shape_table
    {
      get { return _tile_shape_table; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EmbarkTile")]
  public partial class EmbarkTile : global::ProtoBuf.IExtensible
  {
    public EmbarkTile() {}
    
    private int _world_x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"world_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int world_x
    {
      get { return _world_x; }
      set { _world_x = value; }
    }
    private int _world_y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"world_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int world_y
    {
      get { return _world_y; }
      set { _world_y = value; }
    }
    private int _world_z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"world_z", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int world_z
    {
      get { return _world_z; }
      set { _world_z = value; }
    }
    private readonly global::System.Collections.Generic.List<isoworldremote.EmbarkTileLayer> _tile_layer = new global::System.Collections.Generic.List<isoworldremote.EmbarkTileLayer>();
    [global::ProtoBuf.ProtoMember(4, Name=@"tile_layer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<isoworldremote.EmbarkTileLayer> tile_layer
    {
      get { return _tile_layer; }
    }
  

    private int _current_year = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"current_year", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int current_year
    {
      get { return _current_year; }
      set { _current_year = value; }
    }

    private int _current_season = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"current_season", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int current_season
    {
      get { return _current_season; }
      set { _current_season = value; }
    }

    private bool _is_valid = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"is_valid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_valid
    {
      get { return _is_valid; }
      set { _is_valid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TileRequest")]
  public partial class TileRequest : global::ProtoBuf.IExtensible
  {
    public TileRequest() {}
    

    private int _want_x = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"want_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int want_x
    {
      get { return _want_x; }
      set { _want_x = value; }
    }

    private int _want_y = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"want_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int want_y
    {
      get { return _want_y; }
      set { _want_y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapRequest")]
  public partial class MapRequest : global::ProtoBuf.IExtensible
  {
    public MapRequest() {}
    

    private string _save_folder = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"save_folder", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string save_folder
    {
      get { return _save_folder; }
      set { _save_folder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapReply")]
  public partial class MapReply : global::ProtoBuf.IExtensible
  {
    public MapReply() {}
    
    private bool _available;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"available", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool available
    {
      get { return _available; }
      set { _available = value; }
    }

    private int _region_x = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"region_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int region_x
    {
      get { return _region_x; }
      set { _region_x = value; }
    }

    private int _region_y = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"region_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int region_y
    {
      get { return _region_y; }
      set { _region_y = value; }
    }

    private int _region_size_x = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"region_size_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int region_size_x
    {
      get { return _region_size_x; }
      set { _region_size_x = value; }
    }

    private int _region_size_y = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"region_size_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int region_size_y
    {
      get { return _region_size_y; }
      set { _region_size_y = value; }
    }

    private int _current_year = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"current_year", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int current_year
    {
      get { return _current_year; }
      set { _current_year = value; }
    }

    private int _current_season = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"current_season", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int current_season
    {
      get { return _current_season; }
      set { _current_season = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RawNames")]
  public partial class RawNames : global::ProtoBuf.IExtensible
  {
    public RawNames() {}
    
    private bool _available;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"available", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool available
    {
      get { return _available; }
      set { _available = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _inorganic = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"inorganic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> inorganic
    {
      get { return _inorganic; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _organic = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"organic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> organic
    {
      get { return _organic; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"BasicMaterial")]
    public enum BasicMaterial
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"AIR", Value=0)]
      AIR = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OTHER", Value=1)]
      OTHER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INORGANIC", Value=2)]
      INORGANIC = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LIQUID", Value=3)]
      LIQUID = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLANT", Value=4)]
      PLANT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WOOD", Value=5)]
      WOOD = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LiquidType")]
    public enum LiquidType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ICE", Value=0)]
      ICE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WATER", Value=1)]
      WATER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAGMA", Value=2)]
      MAGMA = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"BasicShape")]
    public enum BasicShape
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=0)]
      NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPEN", Value=1)]
      OPEN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WALL", Value=3)]
      WALL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FLOOR", Value=4)]
      FLOOR = 4
    }
  
}