#!/bin/sh
PWD=`dirname "${0}"`
cd "${PWD}"
#thanks to Iriel for figuring this out
OSREV=`uname -r | cut -d. -f1`
if [ "$OSREV" -ge 11 ] ; then
	export DYLD_LIBRARY_PATH="./hack:./libs:./hack/libs"
	export DYLD_FRAMEWORK_PATH="./hack:./libs:./hack/libs"
else
	export DYLD_FALLBACK_LIBRARY_PATH="./hack:./libs:./hack/libs"
	export DYLD_FALLBACK_FRAMEWORK_PATH="./hack:./libs:./hack/libs"
fi

old_tty_settings=$(stty -g)
DYLD_INSERT_LIBRARIES=./hack/libdfhack.dylib ./dwarfort.exe "$@"
stty "$old_tty_settings"
tput sgr0
echo ""
